### ISSUE TITLE
Error while trying to run example

### ISSUE THREAD

**Issue by viavacavi** [WhiteApfel/pycups_po#1]
I tried the example as listed in the readme (I changed only the printer name)

I'm running on Ubuntu 22.04 to a venv setup with Python 3.8

Looks like a neat project!

```
Traceback (most recent call last):
  File "/home/viavacavi/.config/JetBrains/PyCharmCE2022.2/scratches/scratch_4.py", line 3, in <module>
    from pycups_po import PrinterOptionsGenerator
  File "/home/viavacavi/PycharmProjects/viavinyl/venv/lib/python3.8/site-packages/pycups_po/__init__.py", line 1, in <module>
    from .generator import PrinterOptionsGenerator
  File "/home/viavacavi/PycharmProjects/viavinyl/venv/lib/python3.8/site-packages/pycups_po/generator.py", line 5, in <module>
    from .models import OptionValue, PrinterOption
  File "/home/viavacavi/PycharmProjects/viavinyl/venv/lib/python3.8/site-packages/pycups_po/models/__init__.py", line 1, in <module>
    from .options import OptionValue, PrinterOption
  File "/home/viavacavi/PycharmProjects/viavinyl/venv/lib/python3.8/site-packages/pycups_po/models/options.py", line 12, in <module>
    class PrinterOption:
  File "/home/viavacavi/PycharmProjects/viavinyl/venv/lib/python3.8/site-packages/pycups_po/models/options.py", line 16, in PrinterOption
    values: list[OptionValue]
TypeError: 'type' object is not subscriptable
```

**Comment by WhiteApfel** [comment]
Oh yep, I'm used to writing for 3.9+

**Comment by WhiteApfel** [comment]
I changed typing to `typing` in v0.0.2

**Comment by viavacavi** [comment]
Thanks for the quick response.  There is one more thing that needs fixed for 3.8 compatibility - str.removeprefix came with 3.9.  For now I've replaced the call with a call to this added function:

```python
def remove_prefix(text, prefix):
    if text.startswith(prefix):
        return text[len(prefix):]
    return text`
```

**Comment by WhiteApfel** [comment]
👋 Sorry for the long answer. I think that I will change the data retrieval process to not use this construct. There is more information in PPD that can be useful

**Comment by WhiteApfel** [comment]
I'm with good news. Finally got time to fix this issue. 

Now a little about compatibility. I can't (don't want to) support py3.7. Why? All because of `typing.Literal`. It appeared in py3.8. There are, of course, workarounds, but I don't like them. Moreover, py3.7 will soon retire.
